os: linux
dist: xenial
language: python
python:
  - '3.6-dev'
  - '3.7-dev'
before_install:
  - export PATH=/usr/bin:$PATH
  - sudo apt-get update -q
  # Dependency to build dbus-python
  - sudo apt-get install libdbus-1-dev
  # Dependency to build python-discid
  - sudo apt-get install libdiscid0
  # Dependencies for GStreamer1.0
  - sudo apt-get install --yes gstreamer1.0-alsa gstreamer1.0-plugins-bad gstreamer1.0-plugins-base gstreamer1.0-plugins-base-apps gstreamer1.0-plugins-good gstreamer1.0-plugins-ugly gstreamer1.0-libav
  # Dependencies for gi.repository: Gst, GObject, Cairo
  - sudo apt-get install -y libgirepository1.0-dev libcairo2-dev gir1.2-gtk-3.0 gobject-introspection python3-gi python3-gi-cairo gir1.2-gtk-3.0 python3-gst-1.0
install:
  - pip install --upgrade setuptools
  - pip install --upgrade cython
  - pip install pycairo
  - pip install pygobject
  - pip install -e git+https://github.com/freedesktop/dbus-python@master#egg=dbus-python --no-dependencies
  - pip install -e git+https://github.com/fishstiqz/pycdb@master#egg=pycdb --no-dependencies
  - pip install -e git+https://github.com/JonnyJD/python-discid@master#egg=discid --no-dependencies
  - pip install git+git://github.com/opacam/epsilon@python3#egg=Epsilon
  - pip install git+git://github.com/opacam/axiom@python3#egg=Axiom
  - pip install service_identity
  - pip install python-coveralls==2.9.1
  - pip install pycodestyle==2.4.0
  - pip install pylint==2.1.1
  - pip install -e .[test]
script:
  - pycodestyle coherence --ignore=E402,W504
  - pylint -E coherence --rcfile=.pylintrc
  - nosetests --with-coverage --cover-erase --cover-package=coherence --cover-html
after_success:
  - coveralls
